Enable secondary joystick fire button as "jump"
rjaremczak/gng_mega65_r6 pull request #1
Opened 2024-11-01 16:52 UTC by csoren

This small PR enables the secondary fire button on C64-style joysticks as the "jump" button, when the "Up + Fire = Jump" configuration option is disabled.

2024-11-01 19:53 UTC, rjaremczak requested changes
However I don't have a joystick with secondary button to verify this fix, it looks like a legitimate one. Please remove CORE-R6.xpr from the PR as it changes only the local path.

2024-11-01 21:42 UTC, csoren commented
Ugh, sorry about the wrong commit, it has been removed.

2024-11-02 06:44 UTC, rjaremczak approved these changes

2024-11-02 06:44 UTC, merged

2024-11-09 18:27 UTC, rjaremczak commented
Thank you for your contribution :-) There is another issue with joystick port 2, originated probably from M2M framework, as soon as it's fixed I'll compile a new release and publish it.